
language: java


matrix:
  include:
  - jdk: oraclejdk8
    env: BUILD_JDK=ORACLE_JDK_8
  - jdk: oraclejdk11
    env: BUILD_JDK=ORACLE_JDK_11
  allow_failures:
  - env: BUILD_JDK=ORACLE_JDK_11

before_install:
  - pip install --user codecov
after_success:
  - codecov

jobs:
  include:
    - stage: build-test
      jdk: oraclejdk8
      env:
        - FOO=foo
      script: echo "hello world" && mvn test -B
    - 
      script: echo "hello world2" && mvn test -B 
    - stage: back-build
      script: echo "hahahaha"

branches:
  except:
    - appveyor
