
language: java
env:
  - FOO=foo2
  - FOO2=fsdf
jdk:
  - oraclejdk8
  - oraclejdk9
before_install:
  - pip install --user codecov
after_success:
  - codecov

jobs:
  include:
    - stage: build-test
      jdk: oraclejdk8
      env:
        - FOO=foo
      script: echo "hello world" && mvn test -B
    - 
      script: echo "hello world2" && mvn test -B 
    - stage: back-build
      script: echo "hahahaha"

branches:
  except:
    - appveyor
